/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern void initialise_monitor_handles(void);


#define MAX_LEN 256


#define NACK 0xA5
#define ACK 0xF5

void delay(){
	for (uint32_t i=0; i<50000;i++);
}

void delay2(){
	for (uint32_t i=0; i<5000000;i++);
}

/* SPI1_ NSS =  PA4 A2  */
/* SPI1_ CLK  = PA5 D13 */
/* SPI1_ MISO = PA6 D12 */
/* SPI1_ MOSI = PA7 D11 */

void SPI_GPIO_Inits(void){
	GPIO_Handle_t SPI_GPIO_Handle;
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALT;
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinAltFuncMode=5;
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_OPType=GPIO_OPTYPE_PP;
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_NOPU_NOPD;
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
	SPI_GPIO_Handle.pGPIOx=GPIOA;
	GPIO_PeriCloclControl(GPIOA, ENABLE);

	//NSS
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_4;
	GPIO_Init(&SPI_GPIO_Handle);

	//SCK
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_5;
	GPIO_Init(&SPI_GPIO_Handle);

	//MISO
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_6;
	GPIO_Init(&SPI_GPIO_Handle);

	//MOSI
	SPI_GPIO_Handle.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_7;
	GPIO_Init(&SPI_GPIO_Handle);




}

SPI_Handle_t SPI_Handle;
void SPI1_Inits(void){

	SPI_PeriCloclControl(SPI1, ENABLE);
	SPI_Handle.pSPIx=SPI1;
	SPI_Handle.SPI_Config.SPI_DeviceMode=SPI_MASTER;
	SPI_Handle.SPI_Config.SPI_BusConfig=SPI_BCONFIG_FD;
	SPI_Handle.SPI_Config.SPI_Speed=SR_BR_PCLK_DIV_2;
	SPI_Handle.SPI_Config.SPI_DFF=SPI_DFF_8BIT;
	SPI_Handle.SPI_Config.SPI_CPHA=SPI_CPHA_0;
	SPI_Handle.SPI_Config.SPI_CPOL=SPI_CPOL_0;
	SPI_Handle.SPI_Config.SPI_SSM=SPI_SSM_DI;

	SPI_Init(&SPI_Handle);
	//GPIO_IRQITConfig(SPI1_EXCEPTION_IT, ENABLE);
	//GPIO_IRQPRConfig(SPI1_EXCEPTION_IT, IRQ_PR_NO_42);

}

void IT_GPIO_Inits(void){
	GPIO_Handle_t GPIO_IT ={0};
	GPIO_IT.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IT_FT;
	GPIO_IT.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_NOPU_NOPD;
	GPIO_IT.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
	GPIO_IT.pGPIOx=GPIOA;
	GPIO_IT.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_12;
	GPIO_PeriCloclControl(GPIOA, ENABLE);
	GPIO_Init(&GPIO_IT);
	GPIO_IRQITConfig(IRQ_EXTI_15_10, ENABLE);
	GPIO_IRQPRConfig(IRQ_EXTI_15_10, IRQ_PR_NO_15);

}

uint8_t Rcvframe=0;
uint8_t dummy=0xFF;
uint8_t RcvByte;
uint8_t Buff[MAX_LEN];
uint8_t pBuff=0;

int main(void)
{

	initialise_monitor_handles();
	IT_GPIO_Inits();
	SPI_GPIO_Inits();
	SPI1_Inits();
	GPIO_IRQITConfig(IRQ_EXTI_15_10, ENABLE);
	SPI_SSOE_Control(SPI1, ENABLE); //Enable Output in master mode and SPI enabled.
	//SPI_SSI_Control(SPI1,ENABLE); Not required for DISABLED SSM
	SPI_IRQITConfig(EXTI_SPI1_NVIC, ENABLE);

	while(1){
		while(Rcvframe==0){};
		GPIO_IRQITConfig(IRQ_EXTI_15_10, DISABLE);
		//SPI_IRQITConfig(EXTI_SPI1_NVIC, ENABLE);
		SPI_Control(SPI1,ENABLE);
		while(Rcvframe==1){
			while(SPI_SendData_IT(&SPI_Handle, &dummy, 1)==SPI_BUSY_TX);
			while(SPI_ReceiveData_IT(&SPI_Handle, &RcvByte, 1)==SPI_BUSY_RX);
		}
		//

		while(GetFlagStatus(SPI1,SPI_BP_BSY));
		SPI_Control(SPI1,DISABLE);
		printf("%s\n",Buff);
		GPIO_IRQITConfig(IRQ_EXTI_15_10, ENABLE);



	}

}
void EXTI15_10_IRQHandler (void){
	Rcvframe=1;
	GPIO_Handling(GPIO_PIN_12);
}

void SPI1_IRQHandler(void){
	SPI_IRQHandling(&SPI_Handle);

}

void SPI_ApplicationEventCallback(SPI_Handle_t *pSPI_Handle,uint8_t AppEvent){
	if(AppEvent==SPI_EVENT_RX_CMPLT){
		Buff[pBuff++]=RcvByte;
		if(RcvByte=='\0' || pBuff==MAX_LEN){
			Buff[pBuff-1]='\0';
			pBuff=0;
			Rcvframe=0;
		}


	}

}
